### ISSUE TITLE
Missing class?

### ISSUE THREAD

**Issue by TheGreenBandit** [Yimura/GTAV-Classes#113]
CPacket, lots of subclasses it looks like through hxd editor. Example CPacketPedCreate

Also another missing class that could be useful is rage::fwDynamicEntityComponent, currently there is pointer to towards it in fwentity, but it is not defined

**Comment by TheGreenBandit** [comment]
Also is there any way to make an access to CVehicleModelInfo from g_local_player?

**Comment by SkiddyToast** [comment]
The CPacket classes are for replays.

**Comment by TheGreenBandit** [comment]
> The CPacket classes are for replays.

Ah

**Comment by Yimura** [comment]
> Also is there any way to make an access to CVehicleModelInfo from g_local_player?

Just cast the model info to CVehicleModelInfo.

**Comment by Yimura** [comment]
Anyways, obviously we haven't reversed all the classes from the game, only the ones that are relevant and useful to others.

**Comment by TheGreenBandit** [comment]
btw in HXD i found at 01B30950->01B30960 SCRIPT_DATA_VERIFY_EVENT, going down from that there is a alot more events such as GIVE_CONTROL_EVENT, and RESPAWN_PLAYER_PED_EVENT. Looks interesting.  Also check out what @AIdaveloper said in https://github.com/YimMenu/YimMenu/issues/1217 when u have the chance thats also interesting
