### ISSUE TITLE
Vehicle m_velocity

### ISSUE THREAD

**Issue by jknl1337** [Yimura/GTAV-Classes#143]
you have the old m_velocity for vehicles? i cant find it

**Comment by gir489returns** [comment]
I tried finding it in the update, and it seems it was found with dynamic analysis. We've decided to remove it as it's not easy to find and just easier to call GET_ENTITY_VELOCITY for our needs.

**Comment by jknl1337** [comment]
im not invoking natives, since im going external

**Comment by gir489returns** [comment]
https://github.com/Yimura/GTAV-Classes/pull/153 has the fixed m_velocity for CVehicle for 3095, but we are not going to update it going forward as we don't see the purpose.

**Comment by Yimura** [comment]
> #153 has the fixed m_velocity for CVehicle for 3095, but we are not going to update it going forward as we don't see the purpose.

From a completion perspective I'd update it whenever someone makes a PR for it but I don't think we'll go looking for it when we're not actually making use of it.
