### ISSUE TITLE
Add is online to FriendInfo

### ISSUE THREAD

**Issue by ApoIlos** [Yimura/GTAV-Classes#2]
Would be nice if i could check/write if a friend is online

**Comment by Yimura** [comment]
m_friend_state contains information about your friend.

https://github.com/Yimura/GTAV-Classes/blob/d8c62840df3634d9f4dbc848d5720ebc95f8d778/FriendInfo.hpp#L13

If you look at IDA you can see that the game checks if the first bit is set:
![image](https://user-images.githubusercontent.com/24669514/155398643-ee1cd595-34c4-4e7f-9bcc-1a9b3214134c.png)
