### ISSUE TITLE
CNetGamePlayer > get_net_data() inconsistent

### ISSUE THREAD

**Issue by FireFox101889** [Yimura/GTAV-Classes#64]
CNetGamePlayer > get_net_data function seems to be inconsistent with my testing. 

the variable below seems to be available before this (not everything is available for me when you first obtain a CNetGamePlayer e.g: when joining a session)

i found that CNetGamePlayer > CPlayerInfo > m_net_player_data to work much better. is this expected?

**Comment by Yimura** [comment]
Not to be rude but issues are meant for inconsistencies in the classes provided by this repo or alternatively to request new classes to be added.

I checked the subroutine in IDA and all it does it return the exact same.
![image](https://user-images.githubusercontent.com/24669514/200906506-ecd2d067-b30c-444c-8444-0153eac2f3d9.png)
