### ISSUE TITLE
There is no CHomingRocketParams in CAmmoRocketInfo class (0x19C)

### ISSUE THREAD

**Issue by Sacracia** [Yimura/GTAV-Classes#84]
Tested in helicopter and with rocket launcher - each time CAmmoRocketInfo has zero at 0x19C offset

**Comment by SkiddyToast** [comment]
According to the game, there is. The rocket just probably isn't a homing rocket.
![image](https://user-images.githubusercontent.com/45642596/205391990-d736e935-487b-451a-bfa4-289eb62dbe12.png)

**Comment by Sacracia** [comment]
Yeah, that's weird. Missiles are homing in both cases

**Comment by Sacracia** [comment]
Everything is fine - I just didnt notice its a structure)
